### PR TITLE
Embed web build artefacts

### PR DESCRIPTION
**Pull request by tullo**
Uses go:embed instead of go generate for generated web/dist files.

### CODE REVIEW

**Comment by laszlocph** [comment]
This looks like a high quality PR. Let me review it today!

**Comment by soniasingla** [comment]
@tullo congratulations on your first PR 🎉

**Comment by laszlocph** [comment]
The build is failing due to #20 so I ran the tests and the build locally. All looks good.

This is stellar work. :100: Thanks for the implementation and the cleanup of the messy go:generate stuff.
Appreciate the help @tullo

**Review by laszlocph — APPROVED** [review]

**Comment by laszlocph** [comment]
This is closing #16

**Pull request merged**
