### PR TITLE
Gimlet manifest to accept kustomize style patches

### PR DESCRIPTION
**Pull request by tcrst**
template changes for accepting Kustomize patches

todo tests  

#31

### CODE REVIEW

**Comment by laszlocph** [comment]
This is so cool! :raised_hands: 

Could you add a test on `applyPatches`?
That would also demonstrate the usage.

**Comment by tcrst** [comment]
test has been added

**Comment by tcrst** [comment]
Moved the `strategicMergePatches` to root manifest

https://github.com/gimlet-io/gimletd/pull/50

**Comment by laszlocph** [comment]
Test fails due to not having the latest gimletd dep. Merging and fixing on main

**Pull request merged**
