### PR TITLE
adding the possibility to provide multiple paths to gimlet seal command

### PR DESCRIPTION
**Pull request by joelazar**

### CODE REVIEW

**Review by laszlocph — APPROVED** [review]

**Comment by laszlocph** [comment]
- Totally valid use-case, thanks for thinking of it
- CI failed, but only because PRs don't get the secrets injected. Tests pass locally
- Would you mind adding a test for it? `seal_test.go` has some cases that shows how to do it

**Comment by joelazar** [comment]
>     * Totally valid use-case, thanks for thinking of it
> 
>     * CI failed, but only because PRs don't get the secrets injected. Tests pass locally
> 
>     * Would you mind adding a test for it? `seal_test.go` has some cases that shows how to do it. If not that's cool, I'll add them after merge.

Sure, totally cool, I'll try to do it today evening/tomorrow morning :+1:

**Comment by joelazar** [comment]
@laszlocph, did you have something similar in mind?

**Comment by laszlocph** [comment]
This is it. Thanks!

Also for the fixes!

**Pull request merged**
